### ISSUE TITLE
Copy default filename from source

### ISSUE THREAD

**Issue by tofagerl** [danielbrodin/atom-fetch#1]
Would it be possible to copy the default filename from the source so that when I download e.g. jquery, the new file and tab is named jquery.min.css instead of "untitled"?

**Comment by danielbrodin** [comment]
The tab is stilled named "untitled", but it will suggest a filename on save now. I haven't looked to much into the tab name, but i'm pretty sure it's based on it's path which I can't set because then the file will be saved, but might look into it more later. I think the most important thing with this is the filename suggestion on save.

**Comment by tofagerl** [comment]
That doesn't matter, the file needs to be saved anyway. I suppose there is no way to autosave the file?

**Comment by danielbrodin** [comment]
If you instead of using fetch from the command palette right click on a folder in the tree-view and use Fetch from there, it will be saved to that folder instead of being opened :)

**Comment by tofagerl** [comment]
Sire, you exceed my expectations. Salutations!
